# Generated by Django 3.2.6 on 2021-08-26 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Newspaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('photo', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateTimeField()),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.newspaper')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('title', 'date', 'source')},
            },
        ),
    ]
